{{- if and .Values.imageCredentials.create (not .Values.imageCredentials.existingSecret) -}}
{{- if and .Values.imageCredentials.username .Values.imageCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-registry
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imageCredentials.registry .Values.imageCredentials.username .Values.imageCredentials.password (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
{{- else }}
{{- fail "imageCredentials.username and imageCredentials.password must be set when imageCredentials.create is true." }}
{{- end }}
{{- end }}
