{{- if not .Values.gateway.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-secret
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  LICENSE_KEY: {{ .Values.gateway.licenseKey | quote }}
  EDGEE_SIGNATURE_KEY: {{ .Values.gateway.signatureKey | quote }}
  {{- if .Values.gateway.providerKeysContent }}
  provider_keys.toml: {{ .Values.gateway.providerKeysContent | quote }}
  {{- end }}
{{- end }}
