apiVersion: v2
name: gateway
version: 0.6.0
type: application
appVersion: "1.10.1"
description: A Helm chart for deploying the Edgee OnPrem AI Gateway
keywords:
  - edgee
  - gateway
  - llm
  - ai
  - openai
home: https://edgee.ai
sources:
  - https://github.com/edgee-ai/gateway
maintainers:
  - name: KokaKiwi
    email: julianne@edgee.ai
