{{- if not .Values.clickhouse.existingSecret -}}
{{- if or .Values.clickhouse.username .Values.clickhouse.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jaeger.fullname" . }}-clickhouse
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.clickhouse.username | quote }}
  password: {{ .Values.clickhouse.password | quote }}
{{- else }}
{{- fail "Either clickhouse.existingSecret or both clickhouse.username and clickhouse.password must be set." }}
{{- end }}
{{- end }}
