apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger.fullname" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jaeger.selectorLabels" . | nindent 4 }}
  ports:
    - name: healthcheck
      port: 13133
      targetPort: 13133
      protocol: TCP
    - name: jaeger-grpc
      port: 16685
      targetPort: 16685
      protocol: TCP
    - name: jaeger-http
      port: 16686
      targetPort: 16686
      protocol: TCP
